services:
  - type: web
    name: usa-states-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ADMIN_USER
        sync: false
      - key: ADMIN_PASS
        sync: false
      - key: SESSION_SECRET
        generateValue: true
