const Database = require('better-sqlite3');
const path = require('path');

const db = new Database(path.join(__dirname, 'states.db'));
db.pragma('journal_mode = WAL');

const UPDATES = [
  {abbr:"AL",capital:"Montgomery",population:5157699,cities:["Huntsville","Birmingham","Montgomery","Mobile"],universities:["Auburn University","University of Alabama","University of Alabama at Birmingham","Samford University"],schools:["Alabama School of Mathematics and Science (Mobile)","Loveless Academy Magnet High School (Montgomery)","Bob Jones High School (Madison)"],neighborhoods:["Mountain Brook (Birmingham)","Vestavia Hills (Birmingham)","Madison (Huntsville)"]},
  {abbr:"AK",capital:"Juneau",population:741147,cities:["Anchorage","Fairbanks","Juneau","Knik-Fairview"],universities:["University of Alaska Anchorage","University of Alaska Fairbanks","University of Alaska Southeast"],schools:["Cordova Jr/Sr High School (Cordova)","Juneau-Douglas High School (Juneau)","Homer High School (Homer)"],neighborhoods:["Turnagain (Anchorage)","Mid-Hillside (Anchorage)","Rabbit Creek (Anchorage)"]},
  {abbr:"AZ",capital:"Phoenix",population:7582384,cities:["Phoenix","Tucson","Mesa","Chandler"],universities:["Arizona State University","University of Arizona","Northern Arizona University","Grand Canyon University"],schools:["BASIS Peoria (Peoria)","BASIS Oro Valley (Oro Valley)","BASIS Scottsdale (Scottsdale)"],neighborhoods:["Arcadia (Phoenix)","Gilbert (Phoenix metro)","Vistancia (Peoria)"]},
  {abbr:"AR",capital:"Little Rock",population:3089060,cities:["Little Rock","Fayetteville","Fort Smith","Springdale"],universities:["University of Arkansas","Arkansas State University","University of Central Arkansas","University of Arkansas at Little Rock"],schools:["Haas Hall Academy (Bentonville)","Bentonville High School (Bentonville)","Rogers New Technology High School (Rogers)"],neighborhoods:["The Heights (Little Rock)","Hillcrest (Little Rock)","Bentonville (Northwest Arkansas)"]},
  {abbr:"CA",capital:"Sacramento",population:39529000,cities:["Los Angeles","San Diego","San Jose","San Francisco"],universities:["Stanford University","University of California, Berkeley","University of California, Los Angeles","California Institute of Technology"],schools:["Whitney High School (Cerritos)","Lynbrook High School (San Jose)","Troy High School (Fullerton)"],neighborhoods:["Palo Alto (Bay Area)","Beverly Hills (Los Angeles)","Santa Monica (Los Angeles)"]},
  {abbr:"CO",capital:"Denver",population:6036620,cities:["Denver","Colorado Springs","Aurora","Fort Collins"],universities:["Colorado School of Mines","University of Colorado Boulder","Colorado State University","University of Denver"],schools:["D'Evelyn Junior/Senior High School (Lakewood)","Liberty Common Charter School (Fort Collins)","Vail Ski and Snowboard Academy (Vail)"],neighborhoods:["Highlands (Denver)","Washington Park (Denver)","Briargate (Colorado Springs)"]},
  {abbr:"CT",capital:"Hartford",population:3620000,cities:["Bridgeport","Stamford","New Haven","Hartford"],universities:["Yale University","Wesleyan University","Trinity College","Quinnipiac University"],schools:["Staples High School (Westport)","Daniel Hand High School (Madison)","Wilton High School (Wilton)"],neighborhoods:["Greenwich","Darien","West Hartford"]},
  {abbr:"DE",capital:"Dover",population:1069781,cities:["Wilmington","Dover","Newark","Middletown"],universities:["University of Delaware","Delaware State University","Wilmington University"],schools:["Charter School of Wilmington (Wilmington)","Cab Calloway School of the Arts (Wilmington)","Sussex Academy of Arts and Sciences (Georgetown)"],neighborhoods:["Greenville","North Wilmington","Trolley Square (Wilmington)"]},
  {abbr:"FL",capital:"Tallahassee",population:22975900,cities:["Jacksonville","Miami","Tampa","Orlando"],universities:["University of Florida","Florida State University","University of Miami","Florida A&M University"],schools:["Pine View School (Sarasota)","Suncoast Community High School (Riviera Beach)","The Bolles School (Jacksonville)"],neighborhoods:["Naples","Jupiter","Coral Gables (Miami)"]},
  {abbr:"GA",capital:"Atlanta",population:11302748,cities:["Atlanta","Augusta","Columbus","Macon"],universities:["Emory University","Georgia Institute of Technology","University of Georgia","Mercer University"],schools:["Gwinnett School of Mathematics, Science and Technology (Lawrenceville)","Columbus High School (Columbus)","Walton High School (Marietta)"],neighborhoods:["Alpharetta (Atlanta metro)","Buckhead (Atlanta)","Decatur (Atlanta metro)"]},
  {abbr:"HI",capital:"Honolulu",population:1430688,cities:["Honolulu","East Honolulu","Pearl City","Hilo"],universities:["University of Hawaii at Manoa","Hawaii Pacific University","Chaminade University of Honolulu"],schools:["Iolani School (Honolulu)","Punahou School (Honolulu)","Myron B. Thompson Academy (Honolulu)"],neighborhoods:["Kahala (Honolulu)","Diamond Head (Honolulu)","Kailua (Oahu)"]},
  {abbr:"ID",capital:"Boise",population:2058594,cities:["Boise","Meridian","Nampa","Caldwell"],universities:["University of Idaho","Boise State University","Idaho State University","Brigham Young University-Idaho"],schools:["Renaissance High School (Meridian)","North Star Charter School (Eagle)","Sage International School of Boise (Boise)"],neighborhoods:["North End (Boise)","Southeast Boise (Boise)","East Boise (Boise)"]},
  {abbr:"IL",capital:"Springfield",population:12735249,cities:["Chicago","Aurora","Naperville","Joliet"],universities:["University of Illinois Urbana-Champaign","Northwestern University","University of Chicago","University of Illinois Chicago"],schools:["Adlai E. Stevenson High School (Lincolnshire)","Illinois Mathematics and Science Academy (Aurora)","James B. Conant High School (Hoffman Estates)"],neighborhoods:["Lincoln Park (Chicago)","West Loop (Chicago)","Lakeview (Chicago)"]},
  {abbr:"IN",capital:"Indianapolis",population:6970000,cities:["Indianapolis","Fort Wayne","Evansville","South Bend"],universities:["Indiana University Bloomington","Purdue University","University of Notre Dame","Butler University"],schools:["Signature School (Evansville)","West Lafayette Junior/Senior High School (West Lafayette)","Carmel High School (Carmel)"],neighborhoods:["Carmel (Indianapolis metro)","Broad Ripple (Indianapolis)","Meridian-Kessler (Indianapolis)"]},
  {abbr:"IA",capital:"Des Moines",population:3207004,cities:["Des Moines","Cedar Rapids","Davenport","Sioux City"],universities:["University of Iowa","Iowa State University","Drake University"],schools:["Iowa City West High School (Iowa City)","Pleasant Valley High School (Bettendorf)","Ankeny High School (Ankeny)"],neighborhoods:["West Des Moines (Des Moines metro)","Beaverdale (Des Moines)","Waukee (Des Moines metro)"]},
  {abbr:"KS",capital:"Topeka",population:2944380,cities:["Wichita","Overland Park","Kansas City","Olathe"],universities:["University of Kansas","Kansas State University","Wichita State University"],schools:["Blue Valley North High School (Overland Park)","Blue Valley West High School (Overland Park)","Shawnee Mission East High School (Prairie Village)"],neighborhoods:["Lionsgate (Overland Park)","College Hill (Wichita)","Mills Farm (Overland Park)"]},
  {abbr:"KY",capital:"Frankfort",population:4629682,cities:["Louisville","Lexington","Bowling Green","Owensboro"],universities:["University of Kentucky","University of Louisville","Western Kentucky University"],schools:["DuPont Manual High School (Louisville)","Paul Laurence Dunbar High School (Lexington)","Lafayette High School (Lexington)"],neighborhoods:["The Highlands (Louisville)","Crescent Hill (Louisville)","Old Louisville (Louisville)"]},
  {abbr:"LA",capital:"Baton Rouge",population:4560000,cities:["New Orleans","Baton Rouge","Shreveport","Lafayette"],universities:["Louisiana State University","Tulane University","Loyola University New Orleans"],schools:["Louisiana School for Math, Science, and the Arts (Natchitoches)","Benjamin Franklin High School (New Orleans)","Baton Rouge Magnet High School (Baton Rouge)"],neighborhoods:["Garden District (New Orleans)","Uptown (New Orleans)","Lakeview (New Orleans)"]},
  {abbr:"ME",capital:"Augusta",population:1421310,cities:["Portland","Lewiston","Bangor","South Portland"],universities:["University of Maine","Bowdoin College","Colby College","Bates College"],schools:["Maine School of Science and Mathematics (Limestone)","Cape Elizabeth High School (Cape Elizabeth)","Falmouth High School (Falmouth)"],neighborhoods:["Munjoy Hill / East End (Portland)","West End (Portland)","Deering Center (Portland)"]},
  {abbr:"MD",capital:"Annapolis",population:6285380,cities:["Baltimore","Columbia","Germantown","Frederick"],universities:["University of Maryland, College Park","Johns Hopkins University","United States Naval Academy"],schools:["Poolesville High School (Poolesville)","Thomas S. Wootton High School (Rockville)","Winston Churchill High School (Potomac)"],neighborhoods:["Canton (Baltimore)","Federal Hill (Baltimore)","Fells Point (Baltimore)"]},
  {abbr:"MA",capital:"Boston",population:7136171,cities:["Boston","Worcester","Springfield","Cambridge"],universities:["Harvard University","Massachusetts Institute of Technology","Boston College","Tufts University"],schools:["Boston Latin School (Boston)","Dover-Sherborn High School (Dover)","Lexington High School (Lexington)"],neighborhoods:["Beacon Hill (Boston)","Back Bay (Boston)","Harvard Square (Cambridge)"]},
  {abbr:"MI",capital:"Lansing",population:10140459,cities:["Detroit","Grand Rapids","Warren","Sterling Heights"],universities:["University of Michigan","Michigan State University","Michigan Technological University","Wayne State University"],schools:["International Academy (Bloomfield Hills)","International Academy of Macomb (Clinton Township)","Okemos High School (Okemos)"],neighborhoods:["Birmingham (Detroit metro)","Northville (Detroit metro)","Ann Arbor downtown/Old West Side (Ann Arbor)"]},
  {abbr:"MN",capital:"St. Paul",population:5793151,cities:["Minneapolis","St. Paul","Rochester","Bloomington"],universities:["University of Minnesota Twin Cities","Carleton College","Macalester College","St. Olaf College"],schools:["Wayzata High School (Wayzata)","St. Croix Preparatory Academy Upper (Stillwater)","Nova Classical Academy Upper School (St. Paul)"],neighborhoods:["Linden Hills (Minneapolis)","Summit Avenue-Crocus Hill (St. Paul)","Lake Nokomis area (Minneapolis)"]},
  {abbr:"MS",capital:"Jackson",population:2943045,cities:["Jackson","Gulfport","Southaven","Hattiesburg"],universities:["University of Mississippi","Mississippi State University","University of Southern Mississippi"],schools:["Mississippi School for Math and Science (Columbus)","Ocean Springs High School (Ocean Springs)","Lewisburg High School (Olive Branch)"],neighborhoods:["Madison (Jackson metro)","Olive Branch (Memphis metro)","Brandon (Jackson metro)"]},
  {abbr:"MO",capital:"Jefferson City",population:6215607,cities:["Kansas City","St. Louis","Springfield","Columbia"],universities:["Washington University in St. Louis","University of Missouri-Columbia","Saint Louis University","Missouri University of Science and Technology"],schools:["Ladue Horton Watkins High School (St. Louis)","Clayton High School (St. Louis)","Metro Academic and Classical High School (St. Louis)"],neighborhoods:["Central West End (St. Louis)","Ladue (St. Louis metro)","Country Club Plaza area (Kansas City)"]},
  {abbr:"MT",capital:"Helena",population:1137233,cities:["Billings","Missoula","Great Falls","Bozeman"],universities:["Montana State University","University of Montana","Montana Technological University"],schools:["Bozeman High School (Bozeman)","Whitefish High School (Whitefish)","Glacier High School (Kalispell)"],neighborhoods:["Whitefish (Flathead Valley)","Big Sky (Gallatin County)","Helena Valley (Helena)"]},
  {abbr:"NE",capital:"Lincoln",population:2005465,cities:["Omaha","Lincoln","Bellevue","Grand Island"],universities:["University of Nebraska-Lincoln","Creighton University","University of Nebraska Omaha"],schools:["Elkhorn South High School (Omaha)","Lincoln East High School (Lincoln)","Millard North High School (Omaha)"],neighborhoods:["Elkhorn (Omaha)","Papillion (Omaha metro)","Country Club (Lincoln)"]},
  {abbr:"NV",capital:"Carson City",population:3267467,cities:["Las Vegas","Henderson","North Las Vegas","Reno"],universities:["University of Nevada, Reno","University of Nevada, Las Vegas (UNLV)","Nevada State University"],schools:["Davidson Academy (Reno)","Advanced Technologies Academy (Las Vegas)","Foothill High School (Henderson)"],neighborhoods:["Summerlin (Las Vegas)","Green Valley South (Henderson)","Southwest Reno (Reno)"]},
  {abbr:"NH",capital:"Concord",population:1409032,cities:["Manchester","Nashua","Concord","Derry"],universities:["Dartmouth College","University of New Hampshire","Franklin Pierce University","Colby-Sawyer College"],schools:["Hanover High School (Hanover)","Lebanon High School (Lebanon)","Bedford High School (Bedford)"],neighborhoods:["Hanover (Dartmouth area)","Durham (UNH area)","Downtown Portsmouth (Portsmouth)"]},
  {abbr:"NJ",capital:"Trenton",population:9500851,cities:["Newark","Jersey City","Paterson","Elizabeth"],universities:["Princeton University","Rutgers University-New Brunswick","Stevens Institute of Technology","New Jersey Institute of Technology"],schools:["High Technology High School (Lincroft)","Bergen County Academies (Hackensack)","Bergen County Technical High School (Teterboro)"],neighborhoods:["Princeton (Princeton)","Montclair (Essex County)","Hoboken (Hudson County)"]},
  {abbr:"NM",capital:"Santa Fe",population:2130256,cities:["Albuquerque","Las Cruces","Rio Rancho","Santa Fe"],universities:["University of New Mexico","New Mexico State University","New Mexico Institute of Mining and Technology"],schools:["UWC-USA (Montezuma)","Albuquerque Academy (Albuquerque)","Los Alamos High School (Los Alamos)"],neighborhoods:["Nob Hill (Albuquerque)","Sandia Heights (Albuquerque)","Santa Fe Plaza / Downtown (Santa Fe)"]},
  {abbr:"NY",capital:"Albany",population:19867248,cities:["New York City","Buffalo","Rochester","Yonkers"],universities:["Columbia University","Cornell University","New York University","Syracuse University"],schools:["Stuyvesant High School (New York City)","Staten Island Technical High School (Staten Island)","Bronx High School of Science (New York City)"],neighborhoods:["Tribeca (New York City)","Park Slope (New York City)","Elmwood Village (Buffalo)"]},
  {abbr:"NC",capital:"Raleigh",population:10975017,cities:["Charlotte","Raleigh","Greensboro","Durham"],universities:["Duke University","University of North Carolina at Chapel Hill","North Carolina State University","Wake Forest University"],schools:["Cary Academy (Cary)","NC School of Science and Mathematics (Durham)","Green Hope High School (Cary)"],neighborhoods:["Myers Park (Charlotte)","Five Points (Raleigh)","SouthPark (Charlotte)"]},
  {abbr:"ND",capital:"Bismarck",population:796568,cities:["Fargo","Bismarck","Grand Forks","Minot"],universities:["North Dakota State University","University of North Dakota","Minot State University","University of Mary"],schools:["Century High School (Bismarck)","Central High School (Grand Forks)","Oak Grove Lutheran School (Fargo)"],neighborhoods:["Lindenwood (Fargo)","Hawthorne (Fargo)","Downtown Fargo (Fargo)"]},
  {abbr:"OH",capital:"Columbus",population:11812200,cities:["Columbus","Cleveland","Cincinnati","Toledo"],universities:["Ohio State University","Case Western Reserve University","Miami University","Ohio University"],schools:["Ottawa Hills High School (Ottawa Hills)","University School (Hunting Valley)","Columbus Academy (Gahanna)"],neighborhoods:["German Village (Columbus)","Hyde Park (Cincinnati)","Old Brooklyn (Cleveland)"]},
  {abbr:"OK",capital:"Oklahoma City",population:4095393,cities:["Oklahoma City","Tulsa","Norman","Broken Arrow"],universities:["University of Oklahoma","Oklahoma State University","Oklahoma City University","University of Tulsa"],schools:["Oklahoma School of Science and Mathematics (Oklahoma City)","Jenks High School (Jenks)","Classen School of Advanced Studies (Oklahoma City)"],neighborhoods:["Nichols Hills (Oklahoma City)","Brookside (Tulsa)","Midtown Tulsa (Tulsa)"]},
  {abbr:"OR",capital:"Salem",population:4272371,cities:["Portland","Salem","Eugene","Gresham"],universities:["University of Oregon","Oregon State University","Portland State University","Reed College"],schools:["Lakeridge High School (Lake Oswego)","Jesuit High School (Portland)","West Linn High School (West Linn)"],neighborhoods:["Pearl District (Portland)","Laurelhurst (Portland)","Arlington Heights (Portland)"]},
  {abbr:"PA",capital:"Harrisburg",population:13078751,cities:["Philadelphia","Pittsburgh","Allentown","Erie"],universities:["University of Pennsylvania","Carnegie Mellon University","Pennsylvania State University","Villanova University"],schools:["Mercersburg Academy (Mercersburg)","Masterman School (Philadelphia)","Conestoga High School (Berwyn)"],neighborhoods:["Rittenhouse Square (Philadelphia)","Society Hill (Philadelphia)","Squirrel Hill North (Pittsburgh)"]},
  {abbr:"RI",capital:"Providence",population:1112308,cities:["Providence","Cranston","Warwick","Pawtucket"],universities:["Brown University","Rhode Island School of Design","University of Rhode Island","Providence College"],schools:["Barrington High School (Barrington)","Wheeler School (Providence)","Classical High School (Providence)"],neighborhoods:["College Hill (Providence)","Blackstone (Providence)","Fox Point (Providence)"]},
  {abbr:"SC",capital:"Columbia",population:5478831,cities:["Charleston","Columbia","North Charleston","Mount Pleasant"],universities:["University of South Carolina","Clemson University","College of Charleston","Furman University"],schools:["South Carolina Governor's School for Science and Mathematics (Hartsville)","Academic Magnet High School (North Charleston)","Wando High School (Mount Pleasant)"],neighborhoods:["South of Broad (Charleston)","French Quarter (Charleston)","Mount Pleasant (Charleston area)"]},
  {abbr:"SD",capital:"Pierre",population:920000,cities:["Sioux Falls","Rapid City","Aberdeen","Brookings"],universities:["University of South Dakota","South Dakota State University","South Dakota School of Mines & Technology","Augustana University"],schools:["Lincoln High School (Sioux Falls)","O'Gorman High School (Sioux Falls)","Rapid City Stevens High School (Rapid City)"],neighborhoods:["All Saints (Sioux Falls)","Whittier (Sioux Falls)","Canyon Lake (Rapid City)"]},
  {abbr:"TN",capital:"Nashville",population:7315076,cities:["Nashville","Memphis","Knoxville","Chattanooga"],universities:["Vanderbilt University","University of Tennessee, Knoxville","Rhodes College","University of Memphis"],schools:["Hume-Fogg Academic Magnet High School (Nashville)","Lausanne Collegiate School (Memphis)","White Station High School (Memphis)"],neighborhoods:["The Gulch (Nashville)","Belmont-Hillsboro (Nashville)","Belle Meade (Memphis)"]},
  {abbr:"TX",capital:"Austin",population:31709821,cities:["Houston","San Antonio","Dallas","Austin"],universities:["Rice University","University of Texas at Austin","Texas A&M University","Southern Methodist University"],schools:["School for the Talented and Gifted (Dallas)","Liberal Arts and Science Academy (Austin)","Carnegie Vanguard High School (Houston)"],neighborhoods:["River Oaks (Houston)","Highland Park (Dallas)","Alamo Heights (San Antonio)"]},
  {abbr:"UT",capital:"Salt Lake City",population:3500000,cities:["Salt Lake City","West Valley City","West Jordan","Provo"],universities:["Brigham Young University","University of Utah","Utah State University","Westminster University"],schools:["Beehive Science and Technology Academy (Salt Lake City)","Skyline High School (Salt Lake City)","Academy for Math Engineering & Science (Salt Lake City)"],neighborhoods:["Yalecrest (Salt Lake City)","Sugar House (Salt Lake City)","East Bench (Salt Lake City)"]},
  {abbr:"VT",capital:"Montpelier",population:642805,cities:["Burlington","South Burlington","Colchester","Rutland"],universities:["University of Vermont","Middlebury College","Champlain College","Norwich University"],schools:["Champlain Valley Union High School (Hinesburg)","Mt. Mansfield Union High School (Jericho)","South Burlington High School (South Burlington)"],neighborhoods:["Hill Section (Burlington)","New North End (Burlington)","South End (Burlington)"]},
  {abbr:"VA",capital:"Richmond",population:8880000,cities:["Virginia Beach","Chesapeake","Arlington","Norfolk"],universities:["University of Virginia","Virginia Tech","William & Mary","George Mason University"],schools:["Thomas Jefferson High School for Science and Technology (Alexandria)","Langley High School (McLean)","Maggie L. Walker Governor's School (Richmond)"],neighborhoods:["The Fan (Richmond)","Church Hill (Richmond)","Clarendon-Courthouse (Arlington)"]},
  {abbr:"WA",capital:"Olympia",population:8074082,cities:["Seattle","Spokane","Tacoma","Vancouver"],universities:["University of Washington","Washington State University","Gonzaga University","Seattle University"],schools:["Nikola Tesla STEM High School (Redmond)","Newport High School (Bellevue)","International School (Bellevue)"],neighborhoods:["South Lake Union (Seattle)","Wilburton (Bellevue)","Madison Park (Seattle)"]},
  {abbr:"WV",capital:"Charleston",population:1764892,cities:["Charleston","Huntington","Morgantown","Parkersburg"],universities:["West Virginia University","Marshall University","University of Charleston","Shepherd University"],schools:["Morgantown High School (Morgantown)","George Washington High School (Charleston)","Charleston Catholic High School (Charleston)"],neighborhoods:["South Hills (Charleston)","Kanawha City (Charleston)","Suncrest (Morgantown)"]},
  {abbr:"WI",capital:"Madison",population:5988406,cities:["Milwaukee","Madison","Green Bay","Kenosha"],universities:["University of Wisconsin-Madison","Marquette University","University of Wisconsin-Milwaukee","Beloit College"],schools:["Whitefish Bay High School (Whitefish Bay)","Middleton High School (Middleton)","Madison West High School (Madison)"],neighborhoods:["Third Ward (Milwaukee)","Dudgeon-Monroe (Madison)","Maple Bluff (Madison)"]},
  {abbr:"WY",capital:"Cheyenne",population:587618,cities:["Cheyenne","Casper","Gillette","Laramie"],universities:["University of Wyoming","Casper College","Central Wyoming College","Laramie County Community College"],schools:["Jackson Hole High School (Jackson)","Central High School (Cheyenne)","Kelly Walsh High School (Casper)"],neighborhoods:["Old Town Cheyenne (Cheyenne)","Rainsford (Cheyenne)","West Jackson (Jackson)"]}
];

const update = db.prepare(`
  UPDATE states SET capital = ?, population = ?, cities = ?, universities = ?, schools = ?, neighborhoods = ?, updated_at = CURRENT_TIMESTAMP
  WHERE abbr = ?
`);

const tx = db.transaction((rows) => {
  for (const s of rows) {
    update.run(
      s.capital,
      s.population,
      JSON.stringify(s.cities),
      JSON.stringify(s.universities),
      JSON.stringify(s.schools),
      JSON.stringify(s.neighborhoods),
      s.abbr
    );
  }
});

tx(UPDATES);
console.log(`Updated ${UPDATES.length} states with fresh 2025 data.`);

const total = db.prepare('SELECT COUNT(*) as c, SUM(population) as p FROM states').get();
console.log(`Total states in DB: ${total.c}, Total population: ${total.p.toLocaleString('en-US')}`);

db.close();
